In [1]:
import pandas as pd

In [2]:
import numpy as np

In [ ]:
df=pd.DataFrame({'A': [1, 2, 3],
                'v' : [4,5,7,]})

In [ ]:
df

In [ ]:
df= pd.Series([1,4,6,4,np.nan,5,7])

In [ ]:
df

In [5]:
dates=pd.date_range('20000520', periods=10)

### 

In [6]:
dates

DatetimeIndex(['2000-05-20', '2000-05-21', '2000-05-22', '2000-05-23',
               '2000-05-24', '2000-05-25', '2000-05-26', '2000-05-27',
               '2000-05-28', '2000-05-29'],
              dtype='datetime64[ns]', freq='D')

In [7]:
df3=pd.DataFrame(np.random.randn(10,5), index=dates,columns=list('ABCDE'))

In [8]:
df3

A         B         C         D         E
2000-05-20 -1.326728  0.270480 -0.298401 -0.366397 -0.317380
2000-05-21  0.300610  0.228423 -1.720294  0.086436  1.097898
2000-05-22  0.320990 -0.605087 -0.952158  1.808060  2.171840
2000-05-23  0.513012 -1.688942  1.795829  0.413630  1.156678
2000-05-24 -0.275238 -2.087618 -0.123402 -0.357056  0.446195
2000-05-25  1.043232  0.447263 -0.982666  0.977227 -0.019804
2000-05-26  0.130816  0.631851  1.214709 -1.672795 -0.327133
2000-05-27  2.186614  0.569907 -0.257918 -1.190969  0.595678
2000-05-28  0.882515  0.437687 -0.215614 -1.130975 -1.229176
2000-05-29 -0.288368  1.516322  1.505156  0.835170  0.485990

In [9]:
df4=pd.DataFrame({ "A": 1.0,
        "B": pd.Timestamp('20000520'),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",})

In [10]:
df4

A          B    C  D      E    F
0  1.0 2000-05-20  1.0  3   test  foo
1  1.0 2000-05-20  1.0  3  train  foo
2  1.0 2000-05-20  1.0  3   test  foo
3  1.0 2000-05-20  1.0  3  train  foo

In [11]:
df3.head()

A         B         C         D         E
2000-05-20 -1.326728  0.270480 -0.298401 -0.366397 -0.317380
2000-05-21  0.300610  0.228423 -1.720294  0.086436  1.097898
2000-05-22  0.320990 -0.605087 -0.952158  1.808060  2.171840
2000-05-23  0.513012 -1.688942  1.795829  0.413630  1.156678
2000-05-24 -0.275238 -2.087618 -0.123402 -0.357056  0.446195

In [12]:
df4.to_numpy()

array([[1.0, Timestamp('2000-05-20 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2000-05-20 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2000-05-20 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2000-05-20 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [13]:
df3.median()

A    0.310800
B    0.354083
C   -0.236766
D   -0.135310
E    0.466093
dtype: float64

In [14]:
df3.T

2000-05-20  2000-05-21  2000-05-22  2000-05-23  2000-05-24  2000-05-25  \
A   -1.326728    0.300610    0.320990    0.513012   -0.275238    1.043232   
B    0.270480    0.228423   -0.605087   -1.688942   -2.087618    0.447263   
C   -0.298401   -1.720294   -0.952158    1.795829   -0.123402   -0.982666   
D   -0.366397    0.086436    1.808060    0.413630   -0.357056    0.977227   
E   -0.317380    1.097898    2.171840    1.156678    0.446195   -0.019804   

   2000-05-26  2000-05-27  2000-05-28  2000-05-29  
A    0.130816    2.186614    0.882515   -0.288368  
B    0.631851    0.569907    0.437687    1.516322  
C    1.214709   -0.257918   -0.215614    1.505156  
D   -1.672795   -1.190969   -1.130975    0.835170  
E   -0.327133    0.595678   -1.229176    0.485990

In [ ]:
df3.sort_index(axis=1, ascending=False)

In [17]:
df3.loc[dates[0]]

A   -1.326728
B    0.270480
C   -0.298401
D   -0.366397
E   -0.317380
Name: 2000-05-20 00:00:00, dtype: float64

In [19]:
df3.loc["2000-05-21":"2000-05-22", ["A", "B"]]

A         B
2000-05-21  0.30061  0.228423
2000-05-22  0.32099 -0.605087

In [39]:
x=df3.iloc[:,:-1].values

In [40]:
print(x)

[[ 0.2704799  -0.29840131 -0.36639679]
 [ 0.22842311 -1.72029381  0.08643649]
 [-0.60508654 -0.95215769  1.80806018]
 [-1.68894177  1.79582948  0.41362978]
 [-2.08761782 -0.12340212 -0.35705573]
 [ 0.44726322 -0.9826657   0.97722657]
 [ 0.63185145  1.21470914 -1.67279542]
 [ 0.56990653 -0.25791752 -1.19096903]
 [ 0.43768679 -0.21561449 -1.13097485]
 [ 1.51632219  1.50515624  0.83517047]]
