# Create simple class and function

In [22]:
class statistics:
    def add(self, a, b):
        s = a+b
        return s
    def sub(self, a,b):
        s = a-b
        return s

In [26]:
o = statistics()

In [27]:
o.sub(10,20)

-10

In [25]:
obj2 = statistics()

In [8]:
a = 20
b = 30

In [9]:
obj2.add(a, b)

50

# Polymorphism

In [61]:
class polygon:
    def area1(self, a, b): # area of rectangle 
        s = a*b
        return s
    def area(self, a): # area of square
        s = a*a
        return s

In [62]:
obj = polygon()

In [63]:
a = 10
b = 20

In [81]:
class Person:
    def __init__(self, name, idnumber):
        self.name = name
        self.idnumber = idnumber
    def display(self):
        print(name)
        print(idnumber)
        print(self.name)
    def details(self):
        print(f"My name is: {self.name}")
        print(f"IdNumber: {self.idnumber}")

In [86]:
class stats:
    def __init__(self, l):
        self.lst = l
    def mini(self, l):
        m = min(self.lst)
        return m

In [87]:
l = [1,3,6,5,3]

In [89]:
obj = stats(l)

In [90]:
obj.mini()

1

In [88]:
stats(l).mini()

1

In [82]:
obj = Person("Akem", "102")

In [83]:
obj.display("Vasuda", "236")

Vasuda
236
Akem


In [1]:
# Python code to demonstrate how parent constructors
# are called.

# parent class
class Person(object):

	# __init__ is known as the constructor
	def __init__(self, name, idnumber):
		self.name = name
		self.idnumber = idnumber

	def display(self):
		print(self.name)
		print(self.idnumber)
		
	def details(self):
		print("My name is {}".format(self.name))
		print("IdNumber: {}".format(self.idnumber))
	
# child class
class Employee(Person):
	def __init__(self, name, idnumber, salary, post):
		self.salary = salary
		self.post = post

		# invoking the __init__ of the parent class
		Person.__init__(self, name, idnumber)
		
	def details(self):
		print("My name is {}".format(self.name))
		print("IdNumber: {}".format(self.idnumber))
		print("Post: {}".format(self.post))


# creation of an object variable or an instance
a = Employee('Rahul', 886012, 200000, "Intern")

# calling a function of the class Person using
# its instance
a.display()
a.details()


Rahul
886012
My name is Rahul
IdNumber: 886012
Post: Intern


# public, proctected and private(data hiding-data encapsulation)

In [68]:
class car:
    
    def __init__(self,name,age,color):
        self.name=name
        self.color= color
        self.age = age
        

In [69]:
obj=car("riyan",22,"black") 

In [70]:
obj.name

'riyan'

In [71]:
obj.age

22

In [11]:
dir(obj)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'age',
 'color',
 'name',
 'p']

In [17]:
r=car.__reduce__

In [18]:
print(r)

<method '__reduce__' of 'object' objects>


In [25]:
l=obj.__dict__

In [26]:
for i in l.items():
    print(i)
    

('name', 'riyan')
('color', 'black')
('age', 22)


# protected

In [43]:
class car():
    def __init__(self,windo,door,eng):
        self._windo = windo
        self._door= door
        self._eng= eng
        
class truck(car):
    def __init__(self,windo,door,eng,hp):
        super().__init__(windo,door,eng)
        self.hp=hp

In [44]:
Truck= truck (2,3,"petrol",5)

In [ ]:
k= obj

In [32]:
dir(Truck)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_door',
 '_eng',
 '_windo',
 'hp']

In [34]:
Truck.hp

5

In [36]:
Truck._eng

'petrol'

# private

In [41]:
class car():
    def __init__(self,windo,door,eng=34):
        self.__windo = windo #doublee under score lgaya ha isme
        self.__door= door#same here
        self.__eng= eng#same here
        
class Truck(car):
    def __init__(self,windo,door,eng,hp):
        super().__init__(windo,door,eng)
        self.hp=hp

In [42]:
truck= Truck(7,4,"my")

TypeError: __init__() missing 1 required positional argument: 'hp'

In [35]:
k=obj.__dict__

In [36]:
car._car__door

AttributeError: type object 'car' has no attribute '_car__door'

In [50]:
dir(Truck)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_door',
 '_eng',
 '_windo',
 'hp']

In [ ]:
Truck

In [66]:
class Car():
    def __init__(self,windo,door,eng=34):
        self.__windo = windo #doublee under score lgaya ha isme
        self.__door= door#same here
        self.__eng= eng#same here
        

In [75]:
obj=car(7,8,0)

In [76]:
Car.windo=3

In [77]:
l=obj.__dict__

AttributeError: 'car' object has no attribute '__dict__'

In [63]:
for i in l.items():
    print(i)

('name', 7)
('color', 0)
('age', 8)


In [72]:
class Car:
    __slots__=("name","color","age")
    def __init__(self,name,age,color):
        self.name=name
        self.color= color
        self.age = age

In [73]:
c=Car("honda","red",2)

In [74]:
c.model="top"

In [80]:
import numpy as np

In [119]:
s=[[2,3,4,5,6,7,8,8,],[3,4,5,6,7,6,5,4]]

In [120]:
type(s)

list

In [121]:
a=np.array(s)

In [122]:
type(a)

numpy.ndarray

In [123]:
len(a)

2

In [100]:
a=[1,4]

In [90]:
print 

<function print>

In [112]:
len(dir(a))

47

In [114]:
dir(s)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [113]:
from numpy import shape

In [116]:
from numpy import *

In [124]:
shape(a)

(2, 8)

In [126]:
len(dir(a))

162

In [127]:
a.reshape(8,2)



array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 8],
       [3, 4],
       [5, 6],
       [7, 6],
       [5, 4]])

In [130]:
a.reshape(4,4)

array([[2, 3, 4, 5],
       [6, 7, 8, 8],
       [3, 4, 5, 6],
       [7, 6, 5, 4]])

In [135]:
conda install numpy


Note: you may need to restart the kernel to use updated packages.



EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\Anaconda3




Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - numpy


The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 4.14.0-py39haa95532_0


Preparing transaction: ...working... done
Verifying transaction: ...working... failed


In [139]:
np.__version__

'1.21.5'

In [4]:
import math

In [11]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [8]:
input(a.sqrt())

AttributeError: 'list' object has no attribute 'sqrt'

In [15]:
math.prod(65)

TypeError: 'int' object is not iterable

In [20]:
round(4.9)

5

In [22]:
type(4)

str

In [24]:
a=["riyan","boby"]

In [25]:
a.append("riya")

In [26]:
print(a)

['riyan', 'boby', 'riya']


In [30]:
a.insert(1,"oof")

In [31]:
print(a)

['riyan', 'oof', 'oof', 'boby', 'riya']


In [34]:

try:
    a=5/0
except:
        print("value not defined")

value not defined


In [44]:
nums=[1,2,3,4,5,6]
y=[]

In [45]:
for num in nums:
    y.append(num**2)

In [46]:
print(y)

[1, 4, 9, 16, 25, 36]


In [ ]:
for nem in nums:
    

In [50]:
import numpy as np

In [51]:
np.linspace(0,1,45)

array([0.        , 0.02272727, 0.04545455, 0.06818182, 0.09090909,
       0.11363636, 0.13636364, 0.15909091, 0.18181818, 0.20454545,
       0.22727273, 0.25      , 0.27272727, 0.29545455, 0.31818182,
       0.34090909, 0.36363636, 0.38636364, 0.40909091, 0.43181818,
       0.45454545, 0.47727273, 0.5       , 0.52272727, 0.54545455,
       0.56818182, 0.59090909, 0.61363636, 0.63636364, 0.65909091,
       0.68181818, 0.70454545, 0.72727273, 0.75      , 0.77272727,
       0.79545455, 0.81818182, 0.84090909, 0.86363636, 0.88636364,
       0.90909091, 0.93181818, 0.95454545, 0.97727273, 1.        ])

In [67]:
a=np.ones((3,8))

In [69]:
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [58]:
b=np.ones((8,3))

In [59]:
np.dot(a,b)

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [61]:
b=np.ones(1)

In [66]:
np.random.randn(4,3)

TypeError: only size-1 arrays can be converted to Python scalars

In [68]:
np.median(a)

1.0